version: '2.3'
services:
  openpose:
    image: hardlyrichie/openpose-realsteel
    network_mode: host
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    devices: 
      - "/dev/video0:/dev/video0"
    container_name: realsteel
    working_dir: /openpose/
    volumes:
      - ./rs-pose:/openpose/app:cached 


