# base_url = "https://jonathan-kelley.com/FA19_POE_Final/"
base_url = "https://poe.olin.edu/2019/realsteel"
title = "Real Steel"
description = "Olin College Principles of Engineering 2019"


compile_sass = true
highlight_code = true
insert_anchor_links = true
highlight_theme = "kronuz"
build_search_index = true

[extra]
author = "Jonathan Kelley"
intro_title = "POE 2019: Team Real Steel"
heroline = "World's coolest shadow boxing robot"

